services:
  nginx:
    build: ./nginx
    container_name: nginx
    ports:
      - "443:443"
    volumes:
      - node_data:/var/www/nodejs
    depends_on:
      - nodejs
    networks:
      - transcendance
    restart: unless-stopped

  mariadb:
    build: ./mariadb
    container_name: mariadb
    volumes:
      - db_data:/var/lib/mysql
    env_file:
      - ./.env
    networks:
      - transcendance
    restart: unless-stopped

  nodejs:
    build: ./nodejs
    container_name: nodejs
    volumes:
      - node_data:/var/www/nodejs
    depends_on:
      - mariadb
    networks:
      - transcendance
    restart: unless-stopped

volumes:
  db_data:
    name: db_data
  node_data:
    name: node_data

networks:
  transcendance:
    driver: bridge
